[phases.setup]
nixPkgs = ["nodejs_20", "python3", "gcc", "gnumake"]

[phases.install]
cmds = ["cd augur && npm ci"]

[phases.build]
cmds = ["cd augur && npm run build"]

[start]
cmd = "cd augur && node .output/server/index.mjs"
