export const SUBSCRIPTION_DISCLAIMER = `
OMENORA Daily Insights are provided for entertainment, self-reflection, and personal exploration purposes only. OMENORA does not provide medical advice, mental health counseling, financial advice, legal advice, or relationship counseling. Content generated by OMENORA should not be used as the basis for significant life decisions. Users are solely responsible for decisions made in their own lives.

If you are experiencing a mental health crisis, please contact a qualified professional or contact the 988 Suicide and Crisis Lifeline by calling or texting 988.
`

export const REPORT_DISCLAIMER = `
OMENORA reports are AI-generated content provided for entertainment and self-reflection purposes only. Results are interpretive and pattern-based, not diagnostic or clinical. They are based on information provided by the user and do not constitute professional advice of any kind.
`
