export default defineEventHandler((event) => {
  const txt = [
    '# OMENORA Robots.txt',
    '# Last Updated: 2026-04-20',
    '',
    '# ── Primary search engine crawlers ───────────────────────────────────────',
    'User-agent: Googlebot',
    'Allow: /',
    'Allow: /privacy',
    'Allow: /terms',
    'Disallow: /analysis',
    'Disallow: /preview',
    'Disallow: /report',
    'Disallow: /calendar',
    'Disallow: /compatibility',
    'Disallow: /subscription',
    'Disallow: /api/',
    'Crawl-delay: 1',
    '',
    'User-agent: Googlebot-Image',
    'Allow: /',
    'Disallow: /api/',
    '',
    'User-agent: Bingbot',
    'Allow: /',
    'Allow: /privacy',
    'Allow: /terms',
    'Disallow: /analysis',
    'Disallow: /preview',
    'Disallow: /report',
    'Disallow: /calendar',
    'Disallow: /compatibility',
    'Disallow: /subscription',
    'Disallow: /api/',
    'Crawl-delay: 1',
    '',
    'User-agent: Applebot',
    'Allow: /',
    'Allow: /privacy',
    'Allow: /terms',
    'Disallow: /api/',
    'Crawl-delay: 2',
    '',
    '# ── General fallback for all other crawlers ───────────────────────────────',
    'User-agent: *',
    'Allow: /',
    'Allow: /privacy',
    'Allow: /terms',
    'Disallow: /analysis',
    'Disallow: /preview',
    'Disallow: /report',
    'Disallow: /calendar',
    'Disallow: /compatibility',
    'Disallow: /subscription',
    'Disallow: /api/',
    'Crawl-delay: 2',
    '',
    '# ── AI training crawlers — blocked ───────────────────────────────────────',
    'User-agent: GPTBot',
    'Disallow: /',
    '',
    'User-agent: ChatGPT-User',
    'Disallow: /',
    '',
    'User-agent: OAI-SearchBot',
    'Disallow: /',
    '',
    'User-agent: PerplexityBot',
    'Disallow: /',
    '',
    'User-agent: Claude-Web',
    'Disallow: /',
    '',
    'User-agent: ClaudeBot',
    'Disallow: /',
    '',
    'User-agent: anthropic-ai',
    'Disallow: /',
    '',
    'User-agent: CCBot',
    'Disallow: /',
    '',
    'User-agent: Amazonbot',
    'Disallow: /',
    '',
    'User-agent: Meta-ExternalAgent',
    'Disallow: /',
    '',
    'User-agent: Bytespider',
    'Disallow: /',
    '',
    'User-agent: YouBot',
    'Disallow: /',
    '',
    '# ── Sitemap ───────────────────────────────────────────────────────────────',
    'Sitemap: https://omenora.com/sitemap.xml',
  ].join('\n')

  const res = event.node.res
  res.setHeader('Content-Type', 'text/plain; charset=utf-8')
  res.setHeader('Cache-Control', 'public, max-age=86400')
  res.statusCode = 200
  res.end(txt)
})
