import React from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, SafeAreaView } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { TermsScreenProps } from '../navigation/types';
import { colors } from '../theme/colors';

const SECTIONS = [
  {
    title: 'Acceptance of Terms',
    body: 'By accessing or using OMENORA, you agree to be bound by these Terms of Service. If you do not agree, please do not use the service.',
  },
  {
    title: 'Nature of Service',
    body: 'OMENORA provides AI-generated destiny and numerology reports for entertainment and self-reflection purposes. Reports are not a substitute for professional advice — medical, legal, financial, or psychological.',
  },
  {
    title: 'Payments & Refunds',
    body: 'All purchases are one-time payments. We offer a 30-day refund policy. To request a refund, contact support@omenora.com within 30 days of purchase with your order details.',
  },
  {
    title: 'Intellectual Property',
    body: 'All content, reports, and materials generated by OMENORA are owned by OMENORA or its licensors. You may not reproduce, distribute, or resell any report content without written permission.',
  },
  {
    title: 'Limitation of Liability',
    body: 'OMENORA is provided "as is" without warranties of any kind. We are not liable for any indirect, incidental, or consequential damages arising from use of the service.',
  },
  {
    title: 'Governing Law',
    body: 'These terms are governed by applicable law. Any disputes shall be resolved through binding arbitration rather than court proceedings, except where prohibited by law.',
  },
  {
    title: 'Contact',
    body: 'For questions regarding these terms, contact us at support@omenora.com. Last updated: January 2026.',
  },
];

export const TermsScreen: React.FC<TermsScreenProps> = ({ navigation }) => (
  <SafeAreaView style={styles.container}>
    <LinearGradient colors={colors.gradients.cosmic} style={styles.gradient}>
      <ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}>

        <View style={styles.topBar}>
          <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backBtn}>
            <Text style={styles.backArrow}>←</Text>
          </TouchableOpacity>
          <Text style={styles.brand}>OMENORA</Text>
          <View style={styles.spacer} />
        </View>

        <Text style={styles.eyebrow}>LEGAL</Text>
        <Text style={styles.heading}>Terms of Service</Text>
        <Text style={styles.lastUpdated}>Effective January 2026</Text>

        <View style={styles.rule} />

        {SECTIONS.map(({ title, body }) => (
          <View key={title} style={styles.section}>
            <Text style={styles.sectionTitle}>{title}</Text>
            <Text style={styles.sectionBody}>{body}</Text>
          </View>
        ))}
      </ScrollView>
    </LinearGradient>
  </SafeAreaView>
);

const styles = StyleSheet.create({
  container:     { flex: 1, backgroundColor: colors.background.main },
  gradient:      { flex: 1 },
  scroll:        { paddingHorizontal: 24, paddingTop: 16, paddingBottom: 56 },

  topBar:        { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 32 },
  backBtn:       { padding: 6 },
  backArrow:     { fontSize: 22, color: colors.text.primary },
  brand:         { fontSize: 11, letterSpacing: 3, color: colors.text.muted },
  spacer:        { width: 34 },

  eyebrow:       { fontSize: 9, letterSpacing: 2.5, textTransform: 'uppercase', color: colors.gold.medium, marginBottom: 8 },
  heading:       { fontSize: 32, fontWeight: '300', color: colors.text.primary, marginBottom: 6 },
  lastUpdated:   { fontSize: 12, color: colors.text.dim, marginBottom: 24, fontStyle: 'italic' },
  rule:          { height: 1, backgroundColor: 'rgba(255,255,255,0.06)', marginBottom: 28 },

  section:       { marginBottom: 28 },
  sectionTitle:  { fontSize: 12, fontWeight: '600', color: colors.text.secondary, letterSpacing: 0.5, textTransform: 'uppercase', marginBottom: 10 },
  sectionBody:   { fontSize: 14, color: colors.text.tertiary, lineHeight: 24 },
});
